server:
  port: 8081
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/asyncflow?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root@2023
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        min-idle: 1                                          # 最小连接数
        max-active: 8                                         # 最大连接数(默认8)
        max-wait: 1000                                       # 获取连接时的最大等待时间
        min-evictable-idle-time-millis: 300000               # 一个连接在池中最小生存的时间，单位是毫秒
        time-between-eviction-runs-millis: 60000             # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zdf.flowsvr.data
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
